kind: pipeline
type: kubernetes
name: dug_default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - dotnet build
  - dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -o publish

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.kaijucode.com
    files: publish/*
    title: 0.0.1

