kind: pipeline
type: kubernetes
name: dug_default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - dotnet build
  - dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained true -o publish
