kind: pipeline
type: kubernetes
name: dug_default

steps:
- name: build linux-x64
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - dotnet build

- name: package linux-x64
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - echo "Building tagged version ${DRONE_TAG}"
  - sed -i 's~<Version>0.0.1</Version>~<Version>${DRONE_TAG}</Version>~' ./dug.csproj
  - dotnet publish -r linux-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -o publish
  - mv ./publish/dug ./publish/dug-linux-x64 #Rename the binary to its architecture type
  - dotnet tool restore
  - dotnet deb -c Release -r linux-x64 -o ./publish
  - dotnet rpm -c Release -r linux-x64 -o ./publish
  when:
    ref:
    - refs/tags/*.*.*

- name: gitea release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.kaijucode.com
    files:
      - publish/dug-linux-x64
      - publish/*.deb
      - publish/*.rpm
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/*.*.*

