kind: pipeline
type: kubernetes
name: dug_default

steps:
- name: testing mono-choco (build)
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true -o ./win/output

- name: testing mono-choco (pack/push)
  image: linuturk/mono-choco
  environment:
    TEST:
      cats
    CHOCO_API_KEY:
      from_secret: chocolatey_api_key
    GITEA_TOKEN:
      from_secret: gitea_token
  commands:
  - echo $${TEST} | wc -c
  - echo ${CHOCO_API_KEY} | wc -c
  - echo ${GITEA_TOKEN} | wc -c
  - choco pack win/dug.nuspec
  - ls
  - choco push dug.0.0.1.nupkg --api-key ${CHOCO_API_KEY}

- name: build linux-x64
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - dotnet build

- name: Prepare for publishing
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - echo "Publishing tagged version ${DRONE_TAG}"
  - sed -i 's~<Version>0.0.1</Version>~<Version>${DRONE_TAG}</Version>~' ./dug.csproj #Set the Version in the csproj, its the only way to get the packaging tools to respect the version.
  when:
    ref:
    - refs/tags/*.*.*

- name: package linux-x64
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true --self-contained true -o publish
  - mv ./publish/dug ./publish/dug-linux-x64 #Rename the binary to its architecture type
  - dotnet tool restore
  - dotnet deb -c Release -r linux-x64 -o ./publish
  - dotnet rpm -c Release -r linux-x64 -o ./publish
  when:
    ref:
    - refs/tags/*.*.*

- name: build win-x64
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - sed -i 's~<version>0.0.1</version>~<version>${DRONE_TAG}</version>~' ./win/dug.nuspec #Set the Version in the nuspec
  - dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true -o ./win/output
  when:
    ref:
    - refs/tags/*.*.*
    
- name: package/publish win-x64
  image: linuturk/mono-choco
  environment:
    CHOCO_API_KEY:
      from_secret: chocolatey_api_key
  commands:
  - choco pack ./win/dug.nuspec
  - choco push dug.${DRONE_TAG}.nupkg --api-key ${CHOCO_API_KEY} --source https://push.chocolatey.org/
  when:
    ref:
    - refs/tags/*.*.*

- name: gitea release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.kaijucode.com
    files:
      - publish/dug-linux-x64
      - publish/*.deb
      - publish/*.rpm
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/*.*.*

