name: unfrl-dug # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: 0.0.1 # just for humans, typically '1.2+git' or '1.3.2'
summary: A powerful DNS progagation checker that can output in a variety of formats. # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  dug:
    command: ./dug
    plugs:
      - home
      - network
parts:
  dug:
    plugin: dotnet
    dotnet-version: 5.0
    dotnet-runtime-version: '5.0.2'
    source: .
    source-type: local
    override-build: |
      dotnet build -c Release
      dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=true --self-contained true -o $SNAPCRAFT_PART_INSTALL
      chmod 0755 $SNAPCRAFT_PART_INSTALL/dug
